//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldLang
    {
        public int langid { get; set; }
        public string Lang { get; set; }
        public string Header { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Instructions { get; set; }
        public string SectionA { get; set; }
        public string SectionB { get; set; }
        public string CName { get; set; }
        public string CTitle { get; set; }
        public string FacName { get; set; }
        public string FacAddress { get; set; }
        public string FacPhone { get; set; }
        public string SurgeonName { get; set; }
        public string SurgeonEmail { get; set; }
        public string CryolifeRep { get; set; }
        public string RegionMgr { get; set; }
        public string Letter { get; set; }
        public string LetterAck { get; set; }
        public string LetterFinal { get; set; }
        public string LetterNone { get; set; }
        public string LetterSendTo { get; set; }
        public string ReturnSample { get; set; }
        public string ReturnSampleY { get; set; }
        public string ReturnSampleN { get; set; }
        public string RMANumber { get; set; }
        public string Product { get; set; }
        public string SerialLotNumber { get; set; }
        public string UDI { get; set; }
        public string Implanted { get; set; }
        public string DateIncident { get; set; }
        public string DateReported { get; set; }
        public string Outcome { get; set; }
        public string Description { get; set; }
        public string DocumentNumber { get; set; }
        public string EffectiveDate { get; set; }
        public string WelcomeMsg { get; set; }
        public string LangName { get; set; }
        public string EditButton { get; set; }
        public string BackButton { get; set; }
        public string SubmitButton { get; set; }
        public string SubmittedBy { get; set; }
        public string DateSubmitted { get; set; }
        public string DialogMsg { get; set; }
        public string OK { get; set; }
        public string TitleHdr { get; set; }
        public string Confidential { get; set; }
        public string SOP { get; set; }
        public string Welcome { get; set; }
        public string AuthMsg { get; set; }
        public string AuthErrorMsg { get; set; }
        public string AuthNoAccessMsg { get; set; }
        public string AuthOKMsg { get; set; }
        public string LoginUserName { get; set; }
        public string LoginPassword { get; set; }
        public string LoginSubmit { get; set; }
        public string AppTitle { get; set; }
        public string NewForm { get; set; }
        public string Logout { get; set; }
        public string FormError { get; set; }
        public string AdminMenuHeader { get; set; }
        public string AdminMenuAccessControl { get; set; }
        public string AdminMenuLangSetup { get; set; }
        public string LangNameEnglish { get; set; }
        public string AdminLanguage { get; set; }
        public string AdminLanguageCode { get; set; }
        public string FormUpdated { get; set; }
        public string FormAdded { get; set; }
        public string UnsavedChanges { get; set; }
        public string NewLangRecord { get; set; }
        public string DeleteConfirm { get; set; }
        public string KeywordValues { get; set; }
        public string Keyword { get; set; }
        public string KeywordDescription { get; set; }
        public string KeywordValue { get; set; }
        public string AclInstructions { get; set; }
        public string AclGroups { get; set; }
        public string AclGroupsAdmin { get; set; }
        public string AclGroupsIT { get; set; }
    }
}
