//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyword
    {
        public int kid { get; set; }
        public string Category { get; set; }
        public string Keyword1 { get; set; }
        public string Discription { get; set; }
        public string Value { get; set; }
    }
}
